flyway.datasources.default.enabled = true
otel.traces.exporter = 'otlp'

[micronaut]
application.name = 'widgetsSvc'
metrics.enabled = true
security.authentication = 'cookie'

[datasources.default]
url = 'jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
username = 'sa'
password = ''
driver-class-name = 'org.h2.Driver'
dialect = 'H2'

[micronaut.metrics.export.prometheus]
enabled = true
descriptions = true
step = 'PT1M'
